WEB/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('gendocs/', include('genDocs.urls')),
    path('admin/', admin.site.urls),
]

genDocs/urls.py
from django.urls import path

from . import views

app_name = 'gendocs'
urlpatterns = [
    path('', views.index, name = 'index')
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'
urlpatterns = [
    path('', views.index, name = 'index'),
    path('gendocs', views.gendocs, name= 'gendocs')
]

genDocs/models.py
from django.db import models

class Project(models.Model):
    name = models.CharField('Название проекта', max_length=200)
    file_immage = models.CharField('Имя изображения', max_length=200)
    centerW_immage = models.IntegerField('Середина симметрии по вертикали в пикселях')
    name = models.CharField('Название таблицы', max_length=200)
    folder_column = models.CharField('Имя столбца значенями из которого будут использоваться для создания директории в которую будут сохраняться сгенерированные файлы', max_length=200)
    name_column = models.CharField('Имя столбца значения из которого будут браться для создания генерируемых файлов', max_length=200)

    class Meta:
        verbose_name = 'Проект'
        verbose_name_plural = 'Проекты'

class Column(models.Model):
    table = models.ForeignKey(Project, on_delete = models.CASCADE)
    column = models.CharField('Имя столбца значения из которого будут рисоваться на шаблонном изображении', max_length=200)
    y = models.IntegerField('Отступ от верхнего края изображения')

    class Meta:
        verbose_name = 'Столбец'
        verbose_name_plural = 'Столбцы'

home/models.py
from django.db import models

# Create your models here.

genDocs/views.py
from django.shortcuts import render

import os

app_name = 'gendocs'
def index(request):
    templates = os.path.join(app_name,'index.html')
    print(templates)
    return render(request,templates)

home/views.py
from django.shortcuts import render
import os

def index(request):    
    return render(request,os.path.join('home','index.html'))

def gendocs(request):
    return render(request,os.path.join('home','gendocs.html'))

WEB/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
 <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>{% block title %}Государственный служащий{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <script type="text/javascript" src="{% static 'js/code.js' %}"></script>
    {% block js %}{% endblock %}
 </head>
 <body>
    <div id="container">
        <div id="header">{% block header %}{% endblock %}</div>
        <div id="sidebar">{% block sidebar %}{% endblock %}</div>
        <div id="aside">{% block aside %}{% endblock %}</div>
        <div id="content">{% block content %}{% endblock %}</div>
        <div id="footer">{% block footer %}{% endblock %}</div>
    </div> 
 </body>
</html>

WEB/templates/gendocs/index.html
{% extends 'base.html' %}

{% block title %}Генератор документов{% endblock %}

{% block js %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.16.1/jszip.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/xlsx/0.16.1/xlsx.js"></script>
{% endblock %}

{% block header %}Генератор документов{% endblock %}

{% block sidebar %}
<div id="image" class="block">Загрузить изображение<input type='file' id='file_img' accept=".jpg, .jpeg, .png"></div>
<div id="table" class="block">Загрузить таблицу<input type='file' id='file_table' accept=".xlsx" disabled></div>
<div id="sheets" class="block"></div>
<div id="columns" class="block"></div>
{% endblock %}

{% block content %}
<canvas id="img">Your browser does not support the HTML 5 Canvas.</canvas>
{% endblock %}
    

WEB/templates/home/gendocs.html
{% extends 'home/index.html' %}
{% block title %}Генератор документов{% endblock %}
{% block header %}Генератор документов{% endblock %}
{% block content %}<a href="{% url 'gendocs:index'%}">Попробовать</a>{% endblock %}

WEB/templates/home/index.html
{% extends 'base.html' %}
{% block header %}Бесплатные программы ускоряющие работу. Утановка не требуется.{% endblock %}
{% block sidebar %}<li><a href="{% url 'home:gendocs' %}">Генератор документов</a>{% endblock %}